### ISSUE TITLE
Can't find LINQPad

### ISSUE THREAD

**Issue by frankvandenbergh** [codingadventures/LINQBridgeVs#19]
If you install LINQPad on another path that the default one, LINQBridgeVs cannot find it.

**Comment by JeremyThomas** [comment]
Yeah, it would be handy to have the opportunity to tell LINQBridgeVs where to find LINQPad and/or have it find it from the .linq file extension association.

Great work BTW.

**Comment by nbasakuragi** [comment]
Thanks, I will include it in the next release. 

@JeremyThomas you mean to find linqpad from the .linq file extension association in the windows registry?

**Comment by JeremyThomas** [comment]
Yeah, maybe from HKEY_CLASSES_ROOT\LINQPad\shell\open\command

**Comment by nbasakuragi** [comment]
Sounds like a good idea, at least the registry could be read to suggest the initial location.

**Comment by Pavel-Malezhyk** [comment]
I have linqpad5 installed into C:\Program Files (x86)\LINQPad5
but there is the same issue when i start VS2012 with  LINQBridge installed.
Does LINQBridge support linqpad5 and what is default path?

**Comment by codingadventures** [comment]
LINQPad 5 is now support on the latest release
