### ISSUE TITLE
This doesn't do anything

### ISSUE THREAD

**Issue by MTuersley** [codingadventures/LINQBridgeVs#22]
I'm confused... the extension does nothing because both the Enable and Disable options are disabled. LINQPad is installed to its default path, it is the Pro version, and I'm using VS2013 SP4. I've tried and get the same results on 2 different computers however both are Win7 x64 if that makes a difference. What do I need to do or look at to get this working? Thanks!

**Comment by nbasakuragi** [comment]
Hi,

I apologize, this comment fell through the cracks, I'm seeing it only now.

Anyway if you still need some help, I would need to know a few things:

Enable and Disable get enabled once you click on the solution explorer on a project or file inside a project given that the two projects are of type VB or C#. If you would send me the logs I could look into them. Please refer to this last comment[1] to see where logs are located. 

Apologies again for the long delayed answer. 

Thanks.
Giovanni
[1] https://github.com/nbasakuragi/LINQBridgeVs/issues/24#issuecomment-106363376
