### ISSUE TITLE
Linqpad starts but does not display anything

### ISSUE THREAD

**Issue by mcoonrod** [codingadventures/LINQBridgeVs#24]
I have been using linqbridgevs for sometime now and have grown dependent on it, so if you can help....
I just got a new machine, installed all appropriate software, and everything was working fine including linqbridge.
Under direction I remapped my MyDocuments folder to one-drive enterprise and since then when I attempt to use linqbridge I get nothing. I click on the little magnifying glass, Linqpad starts and then nothing but a blank page.
I have remapped my documents folder back to its original location and reinstalled everything except Visual Studio but still no results. If I have to I will reinstall Visual Studio 2013 but would rather not as I don't need a half day down time.
I have helped many coworkers get this tool installed and working while mine remains broken (I know I must be a saint).
I run as admin and have full control over my visualizer directory. Google tells me that I am the only one in the world with this problem and am quite frustrated.
-TIA

**Comment by nbasakuragi** [comment]
First of all thanks for using LINQBridgeVs and for you enthusiasm in using it :-)
It's a bit hard to say, I would need the log files. You can find them, under:

> C:\Users\yourusername\AppData\Local

you will find several folders and you should look into these three:

* LINQBridgeVs
* Grapple
* SInject

If you can zip and send them on to me I will look into them. 

Could you give me more info about the OS as well?

By the way the LINQPad scripts are saved under the folder:

 > My Documents\LINQPad Queries\LINQBridge 

Have you checked if that exists? if not could you try to create it?

Regards,
Giovanni

**Comment by mcoonrod** [comment]
Sorry for the late reply I was on PTO
Here are the log files, I appreciate you looking at them.

The only one I saw that looked problematic is the SInject but I know
nothing about it. I did remove the reference to the NWP.Architecture.Batch
and re-added it because is said it was failing to resolve the reference. I
also opened that project and enabled Linqbridge on it to see if that would
help but no luck.

The LINQPad Queries\LINQBridge and the queries are being created. If I run
the queries I can see the results, so this is a big plus because at least
now I can use it even if I have to find the latest and run it.

OS: Windows 7 Professional
Visual Studio 2013 Premium
I am not sure if it should matter but I do keep my code on a separate drive
than the OS and installed applications

Thanks for the help,

Marty

**Comment by nbasakuragi** [comment]
Hi Marty,

SInject is a library I wrote that "injects" what is necessary to enable all the classes in a library to be serialised by the binaryformatter. 

However I haven't received the log files. Could you send them again? 

if you want you can send them at this address:

linqbridgevs@gmail.com

So the linq files are created in the linqpad query folder and if you execute them manually in LINQPad it works no problem. It seems that when you click on the magnifier glass it doesn't execute the corresponding linq file but it creates it, does it?

**Comment by mcoonrod** [comment]
Attached are the log files (or at least they should be).

Yes, the above statement is true. The linq files get created and I am able
to execute them manually. I just end up with an empty query tab in LinqPad
when I click on the magnifier glass.
Now just to be clear they are not being created to My Documents\LINQPad
Queries\LINQBridg, they are being created in
C:\Users\mcoonrod\OneDrive\Documents\LINQPad Queries\LINQBridge

Thanks again.

**Comment by mcoonrod** [comment]
Hi Marty,

I had a look at the log files. As you already noticed, there are a few
errors in SInject. That library injects, at compile time, the serializable
attribute in your dlls. Thus the errors you see coming through are
generated at compile time and not when you click on the magnifier glass. It
doesn't sound like a big issue though, looking at the other log files it
seems that your objects are serialized correctly and the linq files
created.

I don't think having the linqpad queries on a different folder can be an
issue too. The only drawback is that linqpad doesn't have a mechanism to
communicate with it so I'm using this command script to launch linqpad and
to execute the linq file being generated:

(from DynamicCore.txt):

*LINQPad.exe, C:\Users\mcoonrod\OneDrive - NWP Services
 Corporation\Documents\LINQPad
Queries\\LINQBridge\List(nbatComputeRatesApp.ComputeRatesDrivingCursor).linq
-run*

Could you try to launch it from the command terminal with linqpad already
running and then trying to do the same thing with linqpad not running?

if linqpad starts but the linq query is not executed then that could be the
problem. (I will have to come up with something different).

Thanks for your patience and help :-)

Regards,
Giovanni
