### ISSUE TITLE
2017 version

### ISSUE THREAD

**Issue by abukres** [codingadventures/LINQBridgeVs#28]
When will the 2017 version show up in the marketplace? I was notified a week ago that it was submitted.
Is there a way we can build it ourselves? I built the solution but there was no vsix file produced.

**Comment by nbasakuragi** [comment]
Hi, I'm doing some more testing, and also adding new features to support LINQPad 5. To build it yourself you need to use the "Deploy" configuration and then double click on the VSIX.

**Comment by abukres** [comment]
I changed the configuration to deploy and rebuilt and there was no vsix file created. Please add some good instructions on how to compile this tool. Also putting a vsix file in the Release section helps.
When you say you're adding support for LinqPad 5 does this mean this support doesn't exist now?
Is V15 for Visual Studio 2017? How about I just putting the dll's in the Visualizers folder?

**Comment by codingadventures** [comment]
Hi abukres,

That's very odd. Do you have the visual studio extensibility sdk installed? 

Yes at the moment there is no support for linqpad 5. I've created a new branch called 'experimental' a lot of changes are underway, included support for linqpad 5 and a easier to use UI. 

V15 stands for VS2017.

You're right about documentation and release, I will look into those in the next few days

**Comment by codingadventures** [comment]
A pre-release version of LINQBridgeVs has been added. A VSIX is downloadable from Release
