### ISSUE TITLE
bridged Dictionary<int,ClassX> doesnt load internal IEnumerable property in ClassX

### ISSUE THREAD

**Issue by Pavel-Malezhyk** [codingadventures/LINQBridgeVs#31]
bridged Dictionary<int,ClassX> doesnt load internal IEnumerable property in ClassX. It fill it with null.

public class ClassX
{
    public IEnumerable<ClassY> ys;
}

**Comment by Pavel-Malezhyk** [comment]
Yes - ClassX has IEnumerable<ClassY>, if it has List<ClassY> - all works correctly
public class ClassX
{
public IEnumerable<ClassY> ys {get; set;}
}

**Comment by codingadventures** [comment]
yeah if you open your application exe or dll with ilspy you will notice that the property IEnumerable is marked as non serialized. I will provide a fix soon for that, but it will need some testing too before I release it

**Comment by codingadventures** [comment]
This is fixed and will be available with the next release.
