### ISSUE TITLE
Test with an ASP.net Core project

### ISSUE THREAD

**Issue by vbjay** [codingadventures/LINQBridgeVs#42]
![image](https://user-images.githubusercontent.com/3629489/40241289-9d932bb8-5a88-11e8-8b8d-504527e635b4.png)

![image](https://user-images.githubusercontent.com/3629489/40241359-d33da2d4-5a88-11e8-9daf-93d9d73a8f4c.png)

**Comment by codingadventures** [comment]
Thanks Jay for the heads up. When I tried this extension with a .NET Core project it didn't work, so I'm surprised that it didn't raise an exception within visual studio when you exported your variable. I guess I have to spin up an asp.net core project and see for myself. Just out of curiosity, are you using the latest version of VS2017 (15.7) ?

**Comment by vbjay** [comment]
Yes.

**Comment by codingadventures** [comment]
support for .net core, .net standard is not available. custom debugger visualizers only work on the full .NET framework. There a [user voice suggestion](https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/33344638-custom-debugger-visualizer-for-net-core-apps-in-v) to add them in visual studio. In the upcoming release of LINQBridgeVs 1.4.7 there will be an error if a solution containing un-supported projects is LINQBridged
