### ISSUE TITLE
Remove other DebuggerVisualizers?

### ISSUE THREAD

**Issue by fdncred** [codingadventures/LINQBridgeVs#44]
Why does it appear that upon installation via the vsix all my existing .dlls in the Visualizers folder are now deleted?

**Comment by codingadventures** [comment]
Hi, during installation older auto generated visualisers are deleted to avoid errors during data export [PackageConfigurator]https://github.com/codingadventures/LINQBridgeVs/blob/c3822edd490dba392307fa74407620cab69edb6b/Src/BridgeVs.VsPackage.Helper/Configuration/PackageConfigurator.cs#L274

However this is clearly a bug, only linqbridgevs autogenerated dlls are to be deleted and not just any dll. 

I will fix this in the next release

**Comment by fdncred** [comment]
Totally pissed over this. At least you could've moved them to the recycle bin so I could recover them.

**Comment by codingadventures** [comment]
My apologies. I will fix this bug so that it will delete only its own dlls

**Comment by codingadventures** [comment]
Fixed in the upcoming release
