### ISSUE TITLE
Are anonymous types supported when used inside a list?

### ISSUE THREAD

**Issue by stecydube** [codingadventures/LINQBridgeVs#46]
In trying to display a list with items made from an anonymous type the code in LinqPAD could not be compiled and complained about a possible missing reference.

Part of the generated code:
truck.UnLoadCargo<List<AnonymousType<Guid, String ......

**Comment by codingadventures** [comment]
Hi, it should work with anonymous types, however I can see the error here: AnonymousType
There no such a thing like an AnonymousType class that represents anonymous types. This is clearly a bug, I'll investigate and provide a fix in the next release

**Comment by codingadventures** [comment]
To fix your issue change in the linqpad script 
`
truck.UnLoadCargo<List<AnonymousType 
`
with
`var @object = truck.UnLoadCargo(typeof(IList));
`
That should retrieve the list with the anonymous type. 

I will include a proper fix in the next release

**Comment by codingadventures** [comment]
fixed in the next release
