### ISSUE TITLE
XElement nodes are not serialized correctly

### ISSUE THREAD

**Issue by filippobottega** [codingadventures/LINQBridgeVs#50]
Hello,
  I have an object with a property of type XElement. When I inspect the object I can see all properties in LinqPAD but the only one of type XElement is always Null.

  Regards,
    Filippo.

**Comment by codingadventures** [comment]
Hi Filippo,

Which kind of serialization option are you using? Default is Binary but I guess for Xml export JSON could be more suited. I'd need an example to recreate the test case locally, so if you could provide me with one I'll give it a go.

Cheers

**Comment by codingadventures** [comment]
sure thing. please refer to this section of the [readme here](https://github.com/codingadventures/LINQBridgeVs#bridgevs-option-menu)

just select the last drop down and choose JSON. let me know how it goes and if it works for you.

**Comment by filippobottega** [comment]
Done
but now I have an error:

![image](https://user-images.githubusercontent.com/2587684/44994803-a9036400-afa0-11e8-9049-39780f0f520d.png)

![image](https://user-images.githubusercontent.com/2587684/44994821-b7518000-afa0-11e8-9ffa-0c0dba0c8ae3.png)

Logs.txt

```
2018-09-03T17:39:03.4456702+02:00 BroadCastData to LINQBridgeVsTruck
2018-09-03T17:39:03.5081303+02:00 Loading Cargo
2018-09-03T17:39:05.8370810+02:00 Error during LINQPad execution - 
VisualizerObjectSourceException: Timeout della valutazione
   in Microsoft.VisualStudio.Debugger.VisualizerObjectProvider.GetVisualizerObjectData()
   in Microsoft.VisualStudio.Debugger.VisualizerObjectProvider.Microsoft.VisualStudio.DebuggerVisualizers.IVisualizerObjectProvider.GetData()
   in BridgeVs.DynamicVisualizers.DynamicDebuggerVisualizer.Show(IDialogVisualizerService windowService, IVisualizerObjectProvider objectProvider)
```

**Comment by codingadventures** [comment]
Hmmm does that mean "Function Evaluation Timeout" ?  If that's the case then the issue is serialization is taking a long time. I wonder if the object is big

**Comment by filippobottega** [comment]
Could be...
  I'll try with a sample to understand if the XML loaded in the XElement is too big.

**Comment by filippobottega** [comment]
Tested with JSON serialization without luck: the XElement doesn't work.

```
Public Class Test
  Public Property Element As XElement
End Class
```
`    Dim myX = New Test With {.Element = New XElement("elementName", "This is a test")}`

**Comment by codingadventures** [comment]
I think it's a specific case with XElement then, I'll run a few tests then. Thanks for reporting the issue

**Comment by codingadventures** [comment]
Binary formatter and Json.net don't do a good job with xml. 
XmlSerialization will be available since the next release. Despite it will solve the issue, it's known to be slow and thus it might not be suitable in every situation
