### ISSUE TITLE
Uninstall leaves behind build tasks in Custom.After.Microsoft.Common.targets

### ISSUE THREAD

**Issue by jkewley** [codingadventures/LINQBridgeVs#65]
As stated in title, uninstalling LINQBridgeVs leaves hooks in Custom.After.Microsoft.Common.targets

**Comment by codingadventures** [comment]
Hi, 

There is no uninstaller as of yet, please follow the Uninstall section here
https://github.com/codingadventures/LINQBridgeVs#uninstall there is a manual step which involves the deletion of Custom.After.Microsoft.Common.targets
